import { useState } from 'react'
import { useQueryClient } from '@tanstack/react-query'
import { useAuth } from '../context/auth-context'
import { useApi } from '../hooks/use-api'
import { post, api, errorText } from '../services/api'
import { notify } from '../lib/notify'
import { Button, DetailList, ErrorMessage, Field, Modal, Notice, PageHeading } from '../components/ui'
import { MutationForm } from '../components/MutationForm'
export default function AccountPage(){
  const {user,accept}=useAuth(),cache=useQueryClient(),status=useApi('/auth/totp'),[password,setPassword]=useState(false),[setup,setSetup]=useState(null),[codes,setCodes]=useState(null),[disable,setDisable]=useState(false),[error,setError]=useState('')
  return <><PageHeading title="Tài khoản và bảo mật" description="Thông tin cá nhân và xác thực Microsoft Authenticator."/><ErrorMessage>{error}</ErrorMessage><div className="detail-grid"><section className="panel"><h3>Tài khoản</h3><DetailList items={[["Họ tên",user.hoTen],["Email",user.email],["Vai trò",user.vaiTro.join(', ')]]}/><Button className="mt-6" onClick={()=>setPassword(true)}>Đổi mật khẩu</Button></section><section className="panel"><h3>Microsoft Authenticator</h3><ErrorMessage>{status.error&&errorText(status.error)}</ErrorMessage><DetailList items={[["Trạng thái",status.data?.daBat?'Đã bật':'Chưa bật'],["Mã khôi phục còn lại",status.data?.maKhoiPhucConLai]]}/>{status.data?.daBat?<Button className="mt-6" onClick={()=>setDisable(true)}>Tắt xác thực hai lớp</Button>:<Button className="mt-6" onClick={async()=>{try{setSetup(await post('/auth/totp/ghi-danh'))}catch(e){setError(errorText(e))}}}>Thiết lập Authenticator</Button>}</section></div>
    <Modal open={password} onClose={()=>setPassword(false)} title="Đổi mật khẩu"><MutationForm onClose={()=>setPassword(false)} onSave={async form=>{const result=await post('/auth/change-password',Object.fromEntries(form));accept(result);notify('Đã đổi mật khẩu.')}}><Field label="Mật khẩu hiện tại"><input type="password" name="matKhauCu" required autoComplete="current-password"/></Field><Field label="Mật khẩu mới"><input type="password" name="matKhauMoi" required minLength={8} autoComplete="new-password"/></Field></MutationForm></Modal>
    <Modal open={!!setup} onClose={()=>setSetup(null)} title="Thiết lập Microsoft Authenticator">{setup&&<><div className="qr-frame"><img src={setup.anhQr} alt="QR Authenticator"/></div><details><summary>Khoá nhập bằng tay</summary><code className="secret-key">{setup.biMatChiaNhom}</code></details><MutationForm onClose={()=>setSetup(null)} label="Xác nhận" onSave={async form=>{const result=await post('/auth/totp/xac-nhan',{ma:form.get('ma')});setCodes(result.maKhoiPhuc);await cache.invalidateQueries();notify('Đã bật xác thực hai lớp.')}}><Field label="Mã xác thực 6 số"><input name="ma" required pattern="[0-9]{6}" maxLength={6} inputMode="numeric" autoComplete="one-time-code"/></Field></MutationForm></>}</Modal>
    <Modal open={!!codes} onClose={()=>setCodes(null)} title="Mã khôi phục"><Notice>Chỉ hiển thị một lần. Lưu các mã này ở nơi riêng tư trước khi đóng.</Notice><div className="recovery-grid">{codes?.map(code=><code key={code}>{code}</code>)}</div><Button onClick={()=>{const blob=new Blob([codes.join('\n')],{type:'text/plain'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='bench-console-ma-khoi-phuc.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}>Tải mã khôi phục</Button></Modal>
    <Modal open={disable} onClose={()=>setDisable(false)} title="Tắt xác thực hai lớp"><MutationForm onClose={()=>setDisable(false)} onSave={async form=>{await api.delete('/auth/totp',{data:{matKhau:form.get('matKhau')}});await cache.invalidateQueries();notify('Đã tắt xác thực hai lớp.')}}><Notice>Tài khoản bắt buộc hai lớp có thể không được phép tắt. BE sẽ kiểm tra chính sách.</Notice><Field label="Xác nhận mật khẩu"><input name="matKhau" type="password" autoComplete="current-password" required/></Field></MutationForm></Modal>
  </>
}
