import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useQueryClient } from '@tanstack/react-query'
import { Plus } from 'lucide-react'
import { useAuth } from '../context/auth-context'
import { useApi } from '../hooks/use-api'
import { post, patch, remove, errorText } from '../services/api'
import { notify } from '../lib/notify'
import { matches, date } from '../lib/format'
import { Badge, Button, DataTable, DetailList, ErrorMessage, Field, Modal, PageHeading, Toolbar } from '../components/ui'
import { MutationForm } from '../components/MutationForm'
import { DownloadButton, FileDetailModal } from './FilesPage'
export function ProjectsPage(){
  const {can}=useAuth(),cache=useQueryClient(),navigate=useNavigate(),query=useApi('/projects','BENCH.VIEW'),[q,setQ]=useState(''),[editing,setEditing]=useState(null),[error,setError]=useState('')
  return <><PageHeading title="Dự án" description="Các dự án sử dụng Bench, Vehicle và ECU."/><Toolbar value={q} onSearch={setQ} placeholder="Tìm mã / tên dự án" actions={can('BENCH.CREATE')&&<Button variant="primary" onClick={()=>setEditing({})}><Plus size={14}/>Tạo dự án</Button>}/><ErrorMessage>{error||query.error&&errorText(query.error)}</ErrorMessage><DataTable rows={(query.data||[]).filter(p=>matches(p,q,['ma','ten','moTa']))} loading={query.isLoading} columns={[{key:'ma',label:'Mã dự án'},{key:'ten',label:'Tên dự án'},{key:'moTa',label:'Mô tả'},{key:'soThietBi',label:'Thiết bị',render:p=><Button onClick={()=>navigate('/devices?project='+encodeURIComponent(p.ma))}>{p.soThietBi}</Button>},{key:'actions',label:'Thao tác',render:p=><div className="actions">{can('BENCH.UPDATE')&&<Button onClick={()=>setEditing(p)}>Sửa</Button>}{can('BENCH.DELETE')&&<Button variant="danger" disabled={p.soThietBi>0} onClick={async()=>{if(!window.confirm(`Xoá dự án ${p.ten}?`))return;try{await remove('/projects/'+encodeURIComponent(p.ma));await cache.invalidateQueries();notify('Đã xoá dự án.')}catch(e){setError(errorText(e))}}}>Xoá</Button>}</div>}]}/><Modal open={!!editing} onClose={()=>setEditing(null)} title={editing?.ma?'Sửa dự án':'Tạo dự án'}>{editing&&<MutationForm onClose={()=>setEditing(null)} onSave={async form=>{const body=Object.fromEntries(form);if(editing.ma)await patch('/projects/'+encodeURIComponent(editing.ma),body);else await post('/projects',body);await cache.invalidateQueries();notify('Đã lưu dự án.')}}><Field label="Mã dự án *"><input name="ma" required readOnly={!!editing.ma} defaultValue={editing.ma||''} maxLength={64}/></Field><Field label="Tên dự án *"><input name="ten" required defaultValue={editing.ten||''} maxLength={128}/></Field><Field label="Mô tả"><textarea name="moTa" defaultValue={editing.moTa||''} rows={3}/></Field></MutationForm>}</Modal></>
}
export function AlertsPage(){
  const {can,user}=useAuth(),cache=useQueryClient(),navigate=useNavigate(),[q,setQ]=useState(''),[closed,setClosed]=useState(false),[error,setError]=useState('')
  const query=useApi('/alerts','BENCH.VIEW',{includeClosed:closed},{refetchInterval:5000})
  return <><PageHeading title="Cảnh báo" description="Sự cố và thay đổi kết nối từ client."/><Toolbar value={q} onSearch={setQ} placeholder="Tìm thiết bị / nội dung"><label className="check"><input type="checkbox" checked={closed} onChange={e=>setClosed(e.target.checked)}/>Gồm cảnh báo đã đóng</label></Toolbar><ErrorMessage>{error||query.error&&errorText(query.error)}</ErrorMessage><DataTable rows={(query.data||[]).filter(a=>matches(a,q,['benchCode','message','kind']))} loading={query.isLoading} columns={[{key:'benchCode',label:'Thiết bị'},{key:'kind',label:'Loại'},{key:'message',label:'Nội dung'},{key:'raisedAt',label:'Phát sinh',render:a=>date(a.raisedAt)},{key:'acknowledgedAt',label:'Tiếp nhận',render:a=>a.acknowledgedAt?<>{a.acknowledgedBy}<small>{date(a.acknowledgedAt)}</small></>:<Badge tone="warning">Chưa xác nhận</Badge>},{key:'actions',label:'Thao tác',render:a=><div className="actions"><Button onClick={()=>navigate('/devices/'+encodeURIComponent(a.benchCode))}>Mở thiết bị</Button>{!a.acknowledgedAt&&can('BENCH.UPDATE')&&<Button onClick={async()=>{try{await post(`/alerts/${a.id}/ack?by=${encodeURIComponent(user.email)}`);await cache.invalidateQueries();notify('Đã xác nhận tiếp nhận sự cố.')}catch(e){setError(errorText(e))}}}>Xác nhận</Button>}</div>}]}/></>
}
function RunModal({id,onClose}){
  const detail=useApi(`/runs/${id}`,'REPORT.VIEW'),reports=useApi(`/runs/${detail.data?.cmdId}/report`,'REPORT.VIEW',null,{enabled:!!detail.data?.cmdId}),[file,setFile]=useState(null)
  const run=detail.data?.run
  return <Modal open onClose={onClose} title={`Lượt chạy #${id}`} wide><ErrorMessage>{detail.error&&errorText(detail.error)}</ErrorMessage>{run&&<><DetailList items={[["Thiết bị",run.benchCode],["Testcase",run.testCase],["Plan / Request",run.plan],["Kết quả",run.verdict],["Thời gian",run.durationSeconds==null?'—':run.durationSeconds+' giây'],["Người chạy",run.runBy],["Hoàn tất",date(run.finishedAt)],["Lý do",run.reason],["Mã lệnh",detail.data.cmdId]]}/><h3 className="mt-6">Chi tiết từ client</h3><pre className="json-preview">{detail.data.detail||'Client chưa cung cấp chi tiết.'}</pre><h3 className="mt-6">Bằng chứng / báo cáo</h3><ErrorMessage>{reports.error&&errorText(reports.error)}</ErrorMessage>{(reports.data||[]).map(f=><div className="file-row" key={f.id}><span>{f.tenFile}</span><DownloadButton file={f} kind="report"/><Button onClick={()=>setFile(f)}>Xem file</Button></div>)}{!reports.data?.length&&<p className="muted">Chưa có file bằng chứng.</p>}</>}{file&&<FileDetailModal file={file} kind="report" onClose={()=>setFile(null)}/>}</Modal>
}
export function ReportsPage(){
  const [filters,setFilters]=useState({bench:'',verdict:'',plan:'',from:'',to:''}),[page,setPage]=useState(1),[selected,setSelected]=useState(null),[file,setFile]=useState(null)
  const devices=useApi('/devices','BENCH.VIEW'),query=useApi('/runs','REPORT.VIEW',{...filters,from:filters.from?filters.from+'T00:00:00+07:00':undefined,to:filters.to?filters.to+'T23:59:59.999+07:00':undefined,page,size:20},{refetchInterval:10000}),files=useApi('/runs/reports/recent','REPORT.VIEW',{limit:200})
  const update=(key,value)=>{setFilters(v=>({...v,[key]:value}));setPage(1)}
  return <><PageHeading title="Báo cáo" description="Lượt chạy và file kết quả từ client."/><div className="toolbar"><select aria-label="Thiết bị báo cáo" value={filters.bench} onChange={e=>update('bench',e.target.value)}><option value="">Mọi thiết bị</option>{(devices.data||[]).map(d=><option key={d.code} value={d.code}>{d.code}</option>)}</select><select aria-label="Kết quả" value={filters.verdict} onChange={e=>update('verdict',e.target.value)}><option value="">Mọi kết quả</option>{['pass','fail','unknown'].map(v=><option key={v} value={v}>{v.toUpperCase()}</option>)}</select><input aria-label="Plan / Request" placeholder="Mã plan / Request" value={filters.plan} onChange={e=>update('plan',e.target.value)}/><label className="filter-date">Từ ngày <input type="date" value={filters.from} onChange={e=>update('from',e.target.value)}/></label><label className="filter-date">Đến ngày <input type="date" value={filters.to} onChange={e=>update('to',e.target.value)}/></label></div><ErrorMessage>{query.error&&errorText(query.error)}</ErrorMessage><DataTable rows={query.data?.items||[]} loading={query.isLoading} footer={false} onRow={r=>setSelected(r.id)} columns={[{key:'benchCode',label:'Thiết bị'},{key:'testCase',label:'Testcase / plan',render:r=><>{r.testCase}<small>{r.plan||'—'}</small></>},{key:'verdict',label:'Kết quả',render:r=><Badge tone={r.verdict==='pass'?'success':r.verdict==='fail'?'danger':'neutral'}>{r.verdict.toUpperCase()}</Badge>},{key:'durationSeconds',label:'Thời gian',render:r=>r.durationSeconds==null?'—':r.durationSeconds+' giây'},{key:'runBy',label:'Người chạy'},{key:'finishedAt',label:'Hoàn tất',render:r=>date(r.finishedAt)}]}/><div className="table-footer"><span>{query.data?.total||0} lượt chạy</span><div className="flex gap-2 items-center"><Button disabled={page===1} onClick={()=>setPage(v=>v-1)}>Trước</Button>{page} / {Math.max(1,Math.ceil((query.data?.total||0)/20))}<Button disabled={page*20>=(query.data?.total||0)} onClick={()=>setPage(v=>v+1)}>Sau</Button></div></div><PageHeading title="File báo cáo gần đây"/><ErrorMessage>{files.error&&errorText(files.error)}</ErrorMessage><DataTable rows={files.data||[]} loading={files.isLoading} columns={[{key:'benchCode',label:'Thiết bị'},{key:'testCase',label:'Testcase'},{key:'tenFile',label:'File'},{key:'nhanLuc',label:'Nhận lúc',render:f=>date(f.nhanLuc)},{key:'actions',label:'Thao tác',render:f=><div className="actions"><DownloadButton file={f} kind="report"/><Button onClick={()=>setFile(f)}>Thông tin</Button></div>}]}/>{selected&&<RunModal id={selected} onClose={()=>setSelected(null)}/>} {file&&<FileDetailModal file={file} kind="report" onClose={()=>setFile(null)}/>}</>
}
